# Generated by Django 5.2.6 on 2025-09-25 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_alter_answer_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='user_id',
            field=models.CharField(editable=False, max_length=50, unique=True),
        ),
    ]
