# Generated by Django 5.2.6 on 2025-09-25 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_alter_answer_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='user_id',
            field=models.CharField(editable=False, max_length=50),
        ),
    ]
